server:
  port: 8082
spring:
  application:
    name: note-app
  datasource:
    #    url: jdbc:h2:mem:noteApiDB
    url: jdbc:h2:file:./data/notesdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings

logging:
  level:
    com:
      sm:
        noteApp: TRACE
    reactor:
      netty:
        http:
          client: TRACE
    org:
      springframework:
        web:
          reactive: TRACE
        cloud:
          gateway: TRACE